### ISSUE TITLE
update bulma to 0.8.0

### ISSUE THREAD

**Issue by diomed** [BulmaTemplates/bulma-templates#112]
looking for someone to update bulma to freshly released 0.8.0 version in all templates.

this is ideal for new coders, so be our guest and get yourself some PR's in pocket, 
to win that t-shirt and help open source community.

cheers!

**Comment by diomed** [comment]
just an update, when you're updating (lol)
don't forget to change version number above

from
  `  <!-- Bulma Version 0.7.x -->`

to 

 `  <!-- Bulma Version 0.8.x -->`

**Comment by rene-ph** [comment]
@diomed  could you please assign this issue to me? thanks!

**Comment by diomed** [comment]
totally. the floor is yours :)

**Comment by diomed** [comment]
note that I've already added it to some of them. 
coz one day I was bored. lol.
and I didn't update it in main index file, so that's also 
something you can do.
