### ISSUE TITLE
Remove Google Fonts

### ISSUE THREAD

**Issue by dansup** [BulmaTemplates/bulma-templates#124]
I want to stick with system fonts for a few reasons:

- Improve privacy 
- Faster page loads
- I don't like Open Sans

**Comment by dansup** [comment]
@diomed Do you have any objections?

**Comment by diomed** [comment]
nope. your repo, your call.
anyone who wants can add them with one copy-paste click.
although, would be good to leave at least one template with them, 
just for the reference for newbies.
