### ISSUE TITLE
Template example showing navbar centered pages

### ISSUE THREAD

**Issue by devouk** [BulmaTemplates/bulma-templates#158]
Hi, I wonder if you can explain or how to create a template showing a navbar where the pages are centered and spaced 

I am a noobie to bulma and being trying to play with the examples  and figure out levels / flex to get a layout but struggling (based on desktop layout) 

<-Padding/Margin--> Logo <-- Pages Centred to Space Justify Page Width  --><Login & Signup But><-Padding/Margin-->
                                   I  Logo    |                    Page 1    Page 2    Page 3                  |        Login   Signup |
                                   |  Left      |                    Centered  |  Spaced                           |        Right Align       |
                                   
 Similar to the layout as https://getgrav.cms/ , if you see the home page there is quite a lot of good stuff that could be bulma-ised .  I am looking to create something with the sticky scroll on page menu footer as well :)
 
 Its probably something simple that I am not just seeing :) Thank you

**Comment by devouk** [comment]
Sorry should have added it to the template request ideas ..

**Comment by emkelley** [comment]
Take a look at this, it should get you on the right track I think - https://github.com/jgthms/bulma/issues/1604#issuecomment-422407761

**Comment by devouk** [comment]
@emkelley many thanks for taking your time to reply and show us the reference point. Yep it looks like it will cover my understanding, I just think with a lot of the tutorials online are pre the changes of the navbar where centered was causing issues , so found it hard to reference with the newer syntax / control

Will have a good old bash at it this next week. Might even be able to sort out a template soon :-) . Will close this request 👍
