### ISSUE TITLE
Placeholder as Preview-Image at "Tailsaw Blog Post"-Template

### ISSUE THREAD

**Issue by felix-d1strict** [BulmaTemplates/bulma-templates#171]
Hello,

a placeholder is obviously being used as a preview image here:

![image](https://github.com/BulmaTemplates/bulma-templates/assets/68828301/41ca8041-737e-4d85-96be-0bb2a4eecff9)

https://github.com/BulmaTemplates/bulma-templates/blob/16b1c64709be53bf4cda9e68e56d27bea6f562aa/index.html#L793

**Comment by diomed** [comment]
not really a template issue, if it bothers you send a pr, i'll gladly merge. 
but you should read what I wrote in last release. - it's really last release, 
as far as I'm concerned, until bulma doesnt make an update, or until someone 
doesnt send in new templates you can consider this project dead locked.

**Comment by felix-d1strict** [comment]
Thank you!

> as far as I'm concerned, until bulma doesnt make an update, or until someone doesnt send in new templates you can consider this project dead locked.

Perhaps the next update is not so far away after all:

![image](https://github.com/BulmaTemplates/bulma-templates/assets/68828301/e8ae6377-fefe-4167-ba53-786d56f6cb48)
