### ISSUE TITLE
Bulma update to dark mode messed up demos

### ISSUE THREAD

**Issue by sigg3** [BulmaTemplates/bulma-templates#176]
Since Bulma introduced a dark mode, the demo pages look weird. E.g. the[ admin template](https://bulmatemplates.github.io/bulma-templates/templates/admin.html) is now black where I suppose it was lightgrey or white:

![Screenshot from 2024-04-16 13-55-42](https://github.com/BulmaTemplates/bulma-templates/assets/12447374/e98f73dc-3272-4862-9b11-dff0f8fd71d6)

Is there a simple way to fix this?

Cheers! The templates are awesome and I'd like to continue using them :D

**Comment by Aleordoh** [comment]
Probaste forzar el modo claro?
![image](https://github.com/user-attachments/assets/c3f71358-be3d-4fa1-9e00-5355197e1e80)

Luego Juega con el CSS para darle tu toque

**Comment by sigg3** [comment]
Yes, that works. Thank you!
