### ISSUE TITLE
organization

### ISSUE THREAD

**Issue by diomed** [BulmaTemplates/bulma-templates#81]
what about putting it all under organization?
and inviting others? I thought you liked that idea.

**Comment by dansup** [comment]
@diomed I've been really busy with another project, will setup the domain and org this weekend!

**Comment by diomed** [comment]
u forgot :(

**Comment by dansup** [comment]
@diomed I haven't had time to investigate migrating the GH pages. While I appreciate your enthusiasm, there is nothing preventing contributions in the current state. I will try to get this done when I have time.

**Comment by hugo-dlb** [comment]
This repo was really useful to me :)
I might send in a PR for a template or two :)

**Comment by diomed** [comment]
@hugo-dlb sure mate, please do

**Comment by dansup** [comment]
@diomed Done.

**Comment by diomed** [comment]
@dansup please add @aldi to organization

**Comment by diomed** [comment]
please add @emkelley to organization

**Comment by diomed** [comment]
@dansup FFS, Daniel, whole major point of organization was for other people to participate as well.

**Comment by dansup** [comment]
@diomed I don't even know those people, they can contribute but don't need access. Feel free to start your own org if you feel different.

**Comment by diomed** [comment]
Idea of organization is to have all bulma template creators under one hub.

**Comment by dansup** [comment]
@diomed I have added them as collaborators and made you admin in case you want to add others.
