### ISSUE TITLE
cards.css

### ISSUE THREAD

**Issue by credej** [BulmaTemplates/bulma-templates#98]
Is there any chance you can upload the cards.css file? My cards don't seem to be responsive on mobile, the 3 column layout persists on all devices.

**Comment by diomed** [comment]
It's in CSS folder of templates:
https://github.com/dansup/bulma-templates/blob/master/css/cards.css

**Comment by credej** [comment]
Hmm adding this cards.css file gives me a really cool animated background but it actually made the cards more disorganized. I probably should start from scratch, I may have omitted something important. Thank you for your help.

**Comment by credej** [comment]
I noticed that this demo site (https://dansup.github.io/bulma-templates/templates/cards.html) has the same issue - the layout compacts down to 1 card width in Chrome when adjusting the page width - but does not work on an actual mobile phone (keeps 3 card layout).

**Comment by diomed** [comment]
@lowlevelm could you please take a look at this issue?

I am weak on making pages responsive.

**Comment by lowlevelm** [comment]
The problem is the "flow" element. When it gets deleted, everything is restored. I believe it is because the flow element is 200vw wide, 2x the screen width. Changing the width to 100vw breaks the flow element.

**Comment by phranb** [comment]
Add right: -50vw; to the flow element, this would fix the issue.

**Comment by diomed** [comment]
@phranb would you please make a PR?

**Comment by diomed** [comment]
@joshrosenhanst please, could you take a look @ this, mate?

**Comment by joshrosenhanst** [comment]
No problem I'll take a look

Also, it looks like when the templates got updated to bulma 0.8 some of them are using the wrong CDN for bulma.css (cards, contact, and showcase are affected). I'm gonna submit a PR to fix the bulma CDN issue in a sec

**Comment by dansup** [comment]
@diomed I think we should get rid of the tacky background animation, and clean up the cards a bit. I have some idea for different style cards instead of a grid of the same style.

**Comment by diomed** [comment]
ok, no problem. amend them as you wish.

**Comment by joshrosenhanst** [comment]
Another issue is that the template is missing the responsive meta tag:
`<meta name="viewport" content="width=device-width, initial-scale=1">`

If you add that and remove the background animation #flow elements, it fixes the responsive card issues.

**Comment by diomed** [comment]
@joshrosenhanst we welcome pull requests and merge them As Soon As Seen.
